### ISSUE TITLE
bug: Generating password

### ISSUE THREAD

**Issue by Kubis10** [xEdziu/KeepMyPassword-Desktop#17]
## **Expected behaviour**
App should return password with 4 upper case characters or app should throw other error like: 

> Inputs can't be empty

## **Actual behaviour**
App throw error that sum of all arguments is greater then general lenght. Which is false, because empty in this situation is like 0 so 4+0+0+0<5.

## **Reproduce Steps**
Generate password like in screenshot below

## **Screenshots**

![Zrzut ekranu 2022-03-21 221044](https://user-images.githubusercontent.com/50967586/159364549-11d13240-ca47-458a-8714-06e99072cd5f.png)
![Zrzut ekranu 2022-03-21 221145](https://user-images.githubusercontent.com/50967586/159364551-194c8d65-ab33-4f29-84cb-87f783142bb3.png)

## **Environment**
 - OS: win11
 - App Version: 2.2.1

**Comment by xEdziu** [comment]
## That's a really good issue, that points out something interesting.

Code checks if length of the each input equals to 0.

If it does, code automatically assignes "1" to each empty input, so that nothing really could be empty.

Do you think, that I should throw error messeage instead of auto-completing values?

@kamiloox what are your thoughts about it ?

**Comment by Kubis10** [comment]
From a programming point of view it is good but for a gray user not because user will have wtf why this happen

**Comment by kamiloox** [comment]
This should be repaired. I haven't thought about this in this way as you @xEdziu said that 4+1+1+1<5. I believe it misleads a user.

**Comment by xEdziu** [comment]
Okay, so that clearly need to be done to improve overall UX.
Thanks for feedback @Kubis10 @kamiloox, I will fix this in the nearest future!
