### ISSUE TITLE
bug: Duplicate credentials are possible 

### ISSUE THREAD

**Issue by Bouhfid-Mohamed** [xEdziu/KeepMyPassword-Desktop#81]
## **Actual behaviour**
When I add a new credential (Description, Login and Password) with the same informations as an other that already exist. The new one is inserted even if it already exist.

## **Expected behaviour**
A verification before adding new credentials should be done in order to prevent new credentials if (Login and Password) already exist

## **Reproduce Steps**
1. Add  credentials 
2. Add a new credentials with same informations as the first one
3. The new credentials are created even if they already exist

## **Screenshots**
![image](https://user-images.githubusercontent.com/25286966/185175106-3c4d442e-6639-421c-bedf-e403a7bc4e6b.png)

## **Environment**
 - OS: Windows 10
 - App Version: 3.1.0

**Comment by Bouhfid-Mohamed** [comment]
Hello @xEdziu if you find it's realy a bug , you can assign it to me so I work on the fix

**Comment by xEdziu** [comment]
Hi @Bouhfid-Mohamed, thanks for reaching out, it means the world to me.

Although I see, how it may be concerning for users, I don't believe it is a bug, more an enhancement I would say.

If you would like to contribute to this project and resolve this problem, feel free to fork this project and propose your solution, otherwise, I will maybe try to resolve this, but I don't know when.

Thank you a lot and have a great day!
